{
 "title": "Application Performance",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Writestack",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Overview\n\nWritestack is an online platform that provides publishing infrastructure to newsletter."
   }
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))) by (handler)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[5m]))) by (handler)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(histogram_quantile(0.5, rate(http_request_duration_seconds_bucket[5m]))) by (handler)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic - ops/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (handler)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[5m])) by (handler)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}