{
 "title": "Application Performance / Handlers",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "handler",
    "label": "handler",
    "query": {
     "query": "label_values(http_requests_total,handler)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Handler Performance",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## Handler Performance\n\nThis dashboard provides a detailed overview of RED metrics for handlers as well as providing an overview of the top 10 slowest handlers."
   }
  },
  {
   "title": "Top 10 Slowest Handlers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(10, histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, handler)))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RED Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Traffic - ($handler)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"$handler\"}[5m])",
     "legendFormat": "$handler"
    }
   ]
  },
  {
   "title": "Latency - ($handler)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(http_request_duration_seconds_bucket{handler=\"$handler\"}[5m]))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{handler=\"$handler\"}[5m]))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Error rates - ($handler)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(rate(http_requests_total{status=~\"4..|5..\", handler=\"$handler\"}[5m]) / (rate(http_requests_total{handler=\"$handler\"}[5m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}